"""
Documents and chunks — the knowledge itself.

A *document* is one uploaded file. During ingestion it is split into *chunks*
(~600-token passages). Chunks are what we search and what the LLM reads, so each
chunk stores:

- `content`    the text itself
- `embedding`  a 1536-number vector describing its meaning (for semantic search)
- `tsv`        a Postgres full-text index of its words (for keyword search, Week 3)
- `page_start/page_end/section_title`  where it came from — citations need this
- `tenant_id/collection_id`  copied from the document ("denormalised") so the
  search query can filter by permission without joining the documents table.
"""

import uuid
from datetime import datetime

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    CheckConstraint,
    Computed,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base
from app.db.models.enums import DocumentStatus, sql_in

# Must equal settings.embedding_dim. A column's vector size is fixed in the schema.
EMBEDDING_DIM = 1536


class Document(Base):
    __tablename__ = "documents"
    __table_args__ = (
        # Deduplication: the same file (same SHA-256) can exist only once per tenant.
        UniqueConstraint("tenant_id", "file_hash"),
        CheckConstraint(f"status IN ({sql_in(DocumentStatus)})", name="status"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True, default=uuid.uuid4, server_default=text("gen_random_uuid()")
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("tenants.id", ondelete="CASCADE"), index=True
    )
    collection_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("collections.id", ondelete="CASCADE"), index=True
    )
    title: Mapped[str] = mapped_column(Text)
    filename: Mapped[str] = mapped_column(Text)  # original name, for display only
    mime_type: Mapped[str] = mapped_column(Text)
    storage_path: Mapped[str] = mapped_column(Text)  # generated by us, never user input
    file_hash: Mapped[str] = mapped_column(Text)
    page_count: Mapped[int | None] = mapped_column(Integer)
    status: Mapped[str] = mapped_column(
        String(16), default=DocumentStatus.PENDING, server_default=DocumentStatus.PENDING.value
    )
    error_message: Mapped[str | None] = mapped_column(Text)
    # `metadata` is a reserved attribute name on SQLAlchemy models (Base.metadata),
    # so the Python attribute is `meta` while the column is still called "metadata".
    meta: Mapped[dict] = mapped_column("metadata", JSONB, default=dict, server_default=text("'{}'"))
    uploaded_by: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id"))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class Chunk(Base):
    __tablename__ = "chunks"
    __table_args__ = (
        # HNSW = approximate nearest-neighbour graph index. Without it, every
        # semantic search compares the query with EVERY chunk (fine at 1k chunks,
        # painful at 1M). vector_cosine_ops = the index serves cosine distance (<=>).
        Index(
            "chunks_embedding_hnsw",
            "embedding",
            postgresql_using="hnsw",
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
        # GIN index over the tsvector = fast full-text (keyword) search.
        Index("chunks_tsv_gin", "tsv", postgresql_using="gin"),
        # Every search filters on tenant + collection first.
        Index("chunks_tenant_coll", "tenant_id", "collection_id"),
        # Lets Week 3 metadata filters (e.g. {"property_id": "4B"}) use an index.
        Index("chunks_metadata_gin", "metadata", postgresql_using="gin"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True, default=uuid.uuid4, server_default=text("gen_random_uuid()")
    )
    tenant_id: Mapped[uuid.UUID]
    collection_id: Mapped[uuid.UUID]
    document_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("documents.id", ondelete="CASCADE"), index=True
    )
    chunk_index: Mapped[int] = mapped_column(Integer)  # position within the document
    content: Mapped[str] = mapped_column(Text)
    token_count: Mapped[int] = mapped_column(Integer)
    page_start: Mapped[int | None] = mapped_column(Integer)
    page_end: Mapped[int | None] = mapped_column(Integer)
    section_title: Mapped[str | None] = mapped_column(Text)
    # "Document: <title> | Section: <headings>": embedded and keyword-indexed
    # together with `content` (contextual chunk headers, migration 0003).
    context_header: Mapped[str | None] = mapped_column(Text)
    meta: Mapped[dict] = mapped_column("metadata", JSONB, default=dict, server_default=text("'{}'"))
    embedding: Mapped[list[float]] = mapped_column(Vector(EMBEDDING_DIM))
    # GENERATED column: Postgres computes it from the header + content on every
    # insert/update, so it can never drift out of sync. SQLAlchemy knows not to
    # insert into it. Header words get weight B, content words weight A.
    tsv: Mapped[str] = mapped_column(
        TSVECTOR,
        Computed(
            "setweight(to_tsvector('english', coalesce(context_header, '')), 'B') "
            "|| setweight(to_tsvector('english', content), 'A')",
            persisted=True,
        ),
    )
