"""
Original-file storage.

We keep every uploaded file so we can (a) re-index it later with a better
chunker/embedding model without asking the client to re-upload, and (b) let
users open the original from a citation (Week 5).

Local disk in development; the same interface can be backed by S3-compatible
storage in production. Storage keys are generated by us
(`<tenant_id>/<document_id>.pdf`) — the user's filename is never used as a path,
which rules out path-traversal tricks like "../../etc/passwd".
"""

import shutil
import uuid
from functools import lru_cache
from pathlib import Path

from app.core.config import get_settings


class LocalStorage:
    def __init__(self, root: Path) -> None:
        self.root = root.resolve()
        self.root.mkdir(parents=True, exist_ok=True)
        self.tmp_dir = self.root / ".tmp"
        self.tmp_dir.mkdir(exist_ok=True)

    @staticmethod
    def key_for(tenant_id: uuid.UUID, document_id: uuid.UUID, extension: str) -> str:
        return f"{tenant_id}/{document_id}{extension}"

    def path(self, key: str) -> Path:
        path = (self.root / key).resolve()
        if not path.is_relative_to(self.root):  # defence in depth
            raise ValueError("Storage key escapes the storage root")
        return path

    def save(self, key: str, source: Path) -> None:
        destination = self.path(key)
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(source, destination)

    def delete(self, key: str) -> None:
        self.path(key).unlink(missing_ok=True)


@lru_cache
def get_storage() -> LocalStorage:
    return LocalStorage(get_settings().storage_dir)
